[package]
name = "mpu6050"
version = "0.1.1"
authors = ["Julian Gaal <gjulian@uos.de>"]
edition = "2018"

description = "Platform agnostic driver for MPU6050 6-axis IMU"
repository = "https://github.com/juliangaal/mpu6050"
readme = "README.md"
keywords = ["mpu6050", "imu", "embedded-hal-driver"]
license = "MIT"

[dependencies]
embedded-hal = "0.2.2"
libm = "0.1.2"
